Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,6 +14,55 @@ defaults:
     shell: bash
 
 jobs:
+  commit-msg:
+    name: Commit message check
+    runs-on: ubuntu-18.04
+    strategy:
+      fail-fast: true
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 100
+    - name: Check commit messages
+      run: |
+        if git log --oneline | tail -n +2 | head -n 100 | cut -d ' ' -f2- | grep -q '.\{73\}'; then
+          (echo -n "::error::";
+           echo "Some commit message summary lines are too long. See CONTRIBUTING.md for more information.";
+           echo "Invalid commits:";
+           echo;
+           git log --oneline | tail -n +2 | head -n 100 | cut -d ' ' -f2- | grep '.\{73\}';) | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
+          exit 1;
+        fi
+  clang-format:
+    name: Code formatting check
+    runs-on: ubuntu-18.04
+    strategy:
+      fail-fast: true
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 5
+    - name: Add LLVM apt repository
+      run: |
+        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
+        sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
+    - name: Install clang-format-3.8
+      run: |
+        sudo apt-get update -qq
+        sudo apt-get install -y -qq clang-format-3.8 
+    - name: Run clang-format-3.8
+      run: |
+        . ./util/clang_format_all.sh
+        git clean -f
+    - name: Check formatting
+      run: |
+        git diff --quiet || (
+          (echo -n "::error::";
+          echo "clang-format issues were found. See CONTRIBUTING.md for more information.";
+          echo;
+          git diff;) | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
+          exit 1;
+        )
   macOS:
     name: Mac
     needs: [commit-msg, clang-format]
